# Generated by Django 4.2 on 2023-05-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='text',
            field=models.TextField(default='text'),
            preserve_default=False,
        ),
    ]
